version: '3.5'

services:
  database:
    container_name: kong-database
    image: cassandra:3
    ports:
      - 9042:9042

  migrations:
    links:
      - database
    image: kong:latest
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: database
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
    command: sh -c "while ! nc -z database 9042; do sleep 5; echo wait; done && kong migrations bootstrap"

  kong:
    container_name: kong-app
    links:
      - database
      - app_a
      - app_b
    image: kong:latest
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: post
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444

  konga:
    container_name: konga-ui-app
    image: pantsel/konga:latest
    links:
      - kong
    ports:
      - 1337:1337

  app_a:
    container_name: app-a
    image: jamesw/http-echo-server
    ports:
      - 8081:8080

  app_b:
    container_name: app-b
    image: jamesw/http-echo-server
    ports:
      - 8082:8080
