version: '3.5'

services:
  database:
    container_name: kong-database
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  migrations:
    links:
      - database
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: database
      KONG_PG_USER: postgres
      KONG_PG_DATABASE: postgres
      KONG_PG_PASSWORD: root
    command: sh -c "while ! nc -z database 5432; do sleep 5; echo wait; done && kong migrations bootstrap"

  kong:
    container_name: kong-app
    links:
      - database
      - app_a
      - app_b
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: database
      KONG_PG_USER: postgres
      KONG_PG_DATABASE: postgres
      KONG_PG_PASSWORD: root
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444

  konga:
    container_name: konga-ui-app
    image: pantsel/konga:latest
    links:
      - kong
    ports:
      - 1337:1337

  app_a:
    container_name: app-a
    image: jamesw/http-echo-server
    ports:
      - 8081:8080

  app_b:
    container_name: app-b
    image: jamesw/http-echo-server
    ports:
      - 8082:8080
