version: '3.5'

services:
  cassandra:
    container_name: kong-database
    image: cassandra:3
    ports:
      - 9042:9042

  migrations:
    links:
      - cassandra
    build:
      context: gateway/kong
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
    command: /tmp/wait-for-it.sh -t 60 cassandra:9042 -- kong migrations bootstrap

  kong:
    container_name: kong-app
    links:
      - cassandra
      - app_a
    image: kong:1.1.2-alpine
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444

  app_a:
    container_name: app-a
    build:
      context: api/A
    ports:
      - 8081:80

  app_b:
    container_name: app-b
    build:
      context: api/B
    ports:
      - 8082:80
